// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    EmptyWrapper: typeof import('./src/components/table/empty-wrapper.vue')['default']
    LyAreaSearch: typeof import('./src/components/area/ly-area-search.vue')['default']
    LyBtn: typeof import('./src/components/button/ly-btn.vue')['default']
    LyBtnCreate: typeof import('./src/components/button/ly-btn-create.vue')['default']
    LyBtnReset: typeof import('./src/components/button/ly-btn-reset.vue')['default']
    LyBtnSearch: typeof import('./src/components/button/ly-btn-search.vue')['default']
    LyColumn: typeof import('./src/components/table/column/ly-column.vue')['default']
    LyColumnAction: typeof import('./src/components/table/column/ly-column-action.vue')['default']
    LyColumnExpand: typeof import('./src/components/table/column/ly-column-expand.vue')['default']
    LyColumnIndex: typeof import('./src/components/table/column/ly-column-index.vue')['default']
    LyColumnSelection: typeof import('./src/components/table/column/ly-column-selection.vue')['default']
    LyDialog: typeof import('./src/components/dialog/ly-dialog.vue')['default']
    LyDictRender: typeof import('./src/components/special/ly-dict-render.vue')['default']
    LyForm: typeof import('./src/components/form/form/ly-form.vue')['default']
    LyFormItem: typeof import('./src/components/form/form-item/ly-form-item.vue')['default']
    LyIcon: typeof import('./src/components/special/ly-icon.vue')['default']
    LyInput: typeof import('./src/components/form/form-item/ly-input.vue')['default']
    LyPaging: typeof import('./src/components/special/ly-paging.vue')['default']
    LySelect: typeof import('./src/components/form/form-item/ly-select.vue')['default']
    LyTable: typeof import('./src/components/table/ly-table.vue')['default']
    LyToggle: typeof import('./src/components/special/ly-toggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
