name: "交流讨论"
description: "交流讨论"
title: "[other]: "
labels: ["other"]
body:
  - type: markdown
    attributes:
      value: |
        建议[加群(暂无)]()讨论
        ---
  - type: textarea
    attributes:
      label: '-'
      placeholder: '当然也可以在此处讨论
      '
